### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Ved-un** [Dotz0cat/walld#1]
I don't know why I have this: 

```
$  walld
[1]    2453356 abort (core dumped)  walld
```

linux-lts 5.10.56-1

**Comment by Dotz0cat** [comment]
Your issue is caused by not having any images in the default image directory. So if you want it to startup either put an image in the default image directory. ($HOME/.walld/images) Or change where walld sources the images from in ($HOME/.walld/.walldrc).

Sorry for the inconvenience, I will make sure to add some error messages for when there are no images for walld to source.

**Comment by Ved-un** [comment]
> Проблема вызвана отсутствием изображений в каталоге изображений...

Thank you! ... I understand now
